# Usar a versão LTS
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Instala dependências
RUN npm ci

COPY . .

# --- A CORREÇÃO MÁGICA ---
# Aceita a variável vinda do Railway
ARG VITE_API_BASE_URL
# Torna ela disponível para o comando de build
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

# Agora sim, o build vai enxergar a URL
RUN npm run build

# Instala servidor web
RUN npm install -g serve
RUN chown -R node:node /app
USER node
EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]