FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

ENV FLASK_APP=app.main:app
ENV FLASK_DEBUG=0 

EXPOSE 5000

# MUDANÇA AQUI:
# 1. Roda o init_db.py (cria tabelas UMA vez)
# 2. Se der certo (&&), inicia o gunicorn (4 workers)
CMD python init_db.py && gunicorn -w 4 -b 0.0.0.0:5000 app.main:app